server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # --- 1. ACTIVATION DE LA COMPRESSION GZIP (Boost vitesse) ---
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 1000;
    gzip_comp_level 6;
    gzip_vary on;

    # --- 2. GESTION DU CACHE NAVIGATEUR (Boost chargement) ---
    
    # Mise en cahche des fichiers JS/CSS/Images
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    
    location ~ ^/(index\.html|config\.js)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # --- 3. REDIRECTION SPA (Correction 404) ---
    location / {
        try_files $uri $uri/ /index.html;
    }
}
