version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT_MAPPING:-3000:3000}" # Utilisez une variable d'environnement pour le mapping de port
    environment:
      - PORT=3000 # Le port interne du conteneur reste 3000
      - MONGODB_URI=${MONGODB_URI} # Référence la variable d'environnement MONGODB_URI
